// 여럭 곳에 문자열을 직접 쓰면 오타날 수 있음 -> 하나의 정의처럼 enum으로 참조!
export enum ErrorCode {
  SAVED_ROUTE_NOT_FOUND = 'SAVED_ROUTE_NOT_FOUND',

  SAVED_ROUTE_FORBIDDEN = 'SAVED_ROUTE_FORBIDDEN',

  SAVED_ROUTE_ALREADY_EXISTS = 'SAVED_ROUTE_ALREADY_EXISTS',

  AUTH_TOKEN_REQUIRED = 'AUTH_TOKEN_REQUIRED',

  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',

  VALIDATION_FAILED = 'VALIDATION_FAILED',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
